import Head from 'next/head'
import {Box, Typography, useTheme} from "@mui/material";
import { Title, Navbar, Skills, Experience, Projects, Contact } from "../Components/index";
import {useDispatch} from "react-redux";
import dynamic from "next/dynamic";
import {Slide} from "react-awesome-reveal";



export default function Home() {
  const theme = useTheme();
  const dispatch = useDispatch();

  // Use non SSR components since react-awesome-reveal not compatible
  const AboutMe = dynamic(() => import('../Components/AboutMe'), {ssr: false});

  const headerContainerStyle = {
    width: '100%',
    display: 'flex',
    backgroundColor: 'white'
  }

  const sectionHeaderStyle = {
    fontFamily: theme.typography.sectionHeader,
    fontWeight: 300,
    fontSize: {xs:'2rem', sm:'2.5rem', md: '3rem'},
    ml: 'auto',
    mr: 'auto',
  }

  const spacerStyle = {
    width: '100%',
    height: '40vh',
    backgroundColor: 'white'
  }

  return (
    <Box sx={{width: '100vw', height: '100vh', overflow: 'auto'}}>
      <Head>
        <title>Ryan Tso</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Title />
      <Navbar />

      <Box sx={spacerStyle} />

      <Box sx={headerContainerStyle}>
        <Typography sx={sectionHeaderStyle}>
          About Me
        </Typography>
      </Box>
      <AboutMe />

      <Box sx={spacerStyle} />

      <Box sx={{...headerContainerStyle}}>
        <Box sx={{width: '100%'}}>
        <Slide direction="left">
          <Box sx={{...headerContainerStyle, backgroundColor: theme.palette.skills.header}}>
            <Typography sx={{...sectionHeaderStyle, color: 'white'}}>
              Skills
            </Typography>
          </Box>
        </Slide>
        </Box>
      </Box>
      <Skills />

      <Box sx={spacerStyle} />

      <Box sx={headerContainerStyle}>
        <Typography sx={sectionHeaderStyle}>
          Experience
        </Typography>
      </Box>
      <Experience />

      <Box sx={{height: '1000px', width: '100%', backgroundColor: "grey"}} />



    </Box>
  )
}
