import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {Box} from "@mui/material";
import Title from "../Components/Title";
import Navbar from "../Components/Navbar";
import Skills from "../Components/Skills";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Title />
      <Navbar />

      <Box sx={{height: '1500px', width: '100%', backgroundColor: 'grey'}}/>


    </div>
  )
}
